### ISSUE TITLE
Menu "settings"

### ISSUE THREAD

**Issue by Progressia** [Juro12/python-pong#3]
W ekranie powitalnym przydałoby się proste menu:
-START
-SETTINGS
-EXIT

w ustawieniach dodać opcje:
- Level - w zależności od wybranego poziomu ma się zmieniać prędkość początkowa piłeczki

Dorób proszę tabele wyników. Będzie to wymagało wprowadzenie nazwy gracza, a po zakończonej rozgrywce wyniki mają być przechowywane w pliku.

Podgląd tabeli może być wyłącznie po zakończonej rozgrywce.

**Comment by Juro12** [comment]
Poziomy trudności musiały by też oprócz szybkości piłki zwiększać szybkość przeciwnika
