### ISSUE TITLE
Propozycja przebudowania gry

### ISSUE THREAD

**Issue by Progressia** [Juro12/python-pong#4]
Podczas uruchomienia gry napotkałem problem zacinania się sterowania czy też lagowania. Może to mieć związek z samą biblioteką OpenCV, która często nie jest zoptymalizowana do pracy wieloątkowej. Proponuję przebudować gre tak, żeby wykorzystywała mechaniki biblioteki "pygame".

Dodatkowo fajnie by było, żeby po wyświetleniu wyników gracz był odsyłany (np. po naciśnięciu ENTER) do menu głównego.

Nie widziałem możliwości ustawienia umienia gracza. Może przeoczyłem.

Pozdrawiam i dobra robota ;)

**Comment by Juro12** [comment]
Możliwość ustawienia imienia gracza nie była jeszcze zaimplementowana. Właśnie została wprowadzona jako ostatnia zmiana do #3

**Comment by Juro12** [comment]
Szkielet rozgrywki przeportowany został na bibliotekę pygame. Dodatkowo lekko przeprojektowany został poziom trudności teraz prędkość ruchu piłki będzie zawsze taka sama a zmieniać będzie się agresja przeciwnika.

**Comment by Juro12** [comment]
Gra została przepisana pod bibliotekę Pygame a wszelkie funkcjonalności przywrócone lub zmodyfikowane
