### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Progressia** [Juro12/python-pong#5]
Jest lepiej. Można rozbudować trochę gre, ale przed tym chciałbym, abyś utworzył kolejną gałąź nazwij ją 'dev'. Przejdź do gałęzi 'dev' i tam dodaj jedną funkcjonalność do gry. Chciałbym, żeby w połowie planszy była przeszkadzajka, która ze zbliżoną prędkością do aktualnego poziomu trudności, ale z możliwą do przewidzenia luką, będzie przeszkadzać komputerowi oraz graczowi we wbiciu piłeczki przeciwnikowi.

**Comment by Progressia** [comment]
Sprawdziłem działa to fajnie. Gra jest jeszcze za mało dynamiczna moim zdaniem. Spróbuj dodać mechanizm erozji do paletek. Tak, żeby było widać, gdzie uderzyła piłeczka i żeby paletka się zużywała, a raz na jakiś czas poleci złota piłka, która 'uzdrawia' paletke.
Można jezcze pobawić się fizyką, ale to w następnym kroku.
Zmiany wprowadzaj do gałęzi 'dev'.

**Comment by Juro12** [comment]
System destrukcji paletek działa na zasadzie skracania ich prawo lewo. Należy dodać do schematu zachowań przeciwnika priorytet na złotą piłeczkę w momencie w którym ma już krótką paletkę

**Comment by Juro12** [comment]
Ruch paletki z priorytetem złotej piłeczki jest zabugowany paletka czasami zamiera przy prawej krawędzi
